#!/usr/bin/env -S bash

SRC_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
ARGS="$@"

# HELPERS

NO_COLOR="\033[0m"
RED_COLOR="\033[0;31m"
GREEN_COLOR="\033[0;32m"
YELLOW_COLOR="\033[0;33m"
BLUE_COLOR="\033[0;34m"

echo_red () {
    echo -e "${RED_COLOR}${1}${NO_COLOR}"
}

echo_green () {
    echo -e "${GREEN_COLOR}${1}${NO_COLOR}"
}

echo_blue () {
    echo -e "${BLUE_COLOR}${1}${NO_COLOR}"
}

echo_yellow () {
    echo -e "${YELLOW_COLOR}${1}${NO_COLOR}"
}

ensure_installed () {
    if ! $(which $1 > /dev/null); then
        echo_yellow "Installing $1 .. "
        sudo apt-get install -y $1
    else
        echo_green "$1 already installed."
    fi
}

ensure_elvish_installed () {
    if ! $(which elvish > /dev/null); then
	local TMPDIR="$(mktemp -d)"
        local FILE="elvish-v0.19.2"

        echo_yellow "Installing elvish .. "
        cd "${TMPDIR}"

	wget "https://dl.elv.sh/linux-amd64/${FILE}.tar.gz"
        tar xvf "${FILE}.tar.gz"
        chmod +x "${FILE}"
        sudo cp "${FILE}" "/usr/local/bin/elvish"

        cd -
        rm -rf "${TMPDIR}"
    else
        echo_green "elvish already installed."
    fi
}

ensure_gcm_installed () {
    if ! $(git config --global credential.helper > /dev/null); then
	local TMPDIR="$(mktemp -d)"
        local VER=2.4.1
        local DEB_FILE="gcm-linux_amd64.${VER}.deb"
        local URL="https://github.com/git-ecosystem/git-credential-manager/releases/download/v${VER}/${DEB_FILE}"

        echo_yellow "Installing gcm .. "
        cd "${TMPDIR}"

	wget "${URL}"
	sudo dpkg -i "${DEB_FILE}"
        git-credential-manager configure

        cd -
        rm -rf "${TMPDIR}"
    else
        echo_green "gcm already installed."
    fi
}

# MAIN

ensure_installed wget
ensure_installed vim
ensure_installed git
ensure_gcm_installed
ensure_elvish_installed

